# Don't double-build PR commits. See: http://stackoverflow.com/a/31882307/1877326
branches:
  only: 
    - master
sudo:
  false
language: python
addons:
  postgresql: 9.4
  apt:
    packages:
      - build-essential
      - fontforge
      - gettext
      - git-core
      - libpcre3
      - libpcre3-dev
      - libpq-dev
cache:
  directories:
    - $HOME/.pip-download-cache
    - node_modules
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - grunt copy:fonts
  - npm run build-production
  - coverage run --source='hub,kpi,kobo' --omit='*/tests/*,*/migrations/*,*/management/commands/*' manage.py test
  - npm run test
after_script:
  - coverage xml && python-codacy-coverage -r coverage.xml
  - coveralls
env:
  - PIP_DOWNLOAD_CACHE=$HOME/.pip-download-cache DJANGO_DEBUG=False DJANGO_SECRET_KEY=ZGtvYm90cmF2aXM DJANGO_SETTINGS_MODULE=kobo.settings DATABASE_URL="postgres://postgres@localhost:5432/travis_ci_test" TRAVIS_NODE_VERSION="6"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g install npm@latest
  - npm config set strict-ssl false && npm install --save-dev
  - bower install
  - pip install --upgrade 'pip>=8.0' wheel
  - pip install pip-tools
  - pip-sync requirements/requirements.txt
  - pip install coverage codacy-coverage python-coveralls
